version: 0.2

phases:
  post_build:
    commands:
      - mvn -Dmaven.test.skip=true clean package
      - cp pom.xml build/
      - cp target/*.jar build/
artifacts:
  files:
    - '*'
  base-directory: 'build'
